# async await

async await는 swift 5.5 부터 제공하고 있다. 

async await는 기존의 비동기 처리에서 completion Handler 방식을 편하게 해주고 있다.

비동기 처리를 동기처럼 보이게 해결해줄 수 있다. 이는 밑의 사용처 코드에서 확인해볼 수 있다.

비동기 작업이 많아지고 오류 처리, 비동기 호출이 많아질 수록 코드는 복잡해지고 문제가 되기도 한다.

이는 URLSession에서도 강력하게 기능을 발휘하고 있다.

먼저 URLSession과 completionHandler를 활용해서 하는 것을 보도록 하자.

```swift
struct NetworkManager {
    private var session: URLSessionProtocol
    
    init(session: URLSessionProtocol = URLSession.shared) {
        self.session = session
    }
    
    mutating func execute(
        with apiAble: APIable,
        completion: @escaping (Result<Data, NetworkError>)
        -> Void) {
        let successRange = 200...299
        var request: URLRequest?
        
        switch apiAble.method {
        case .get:
            var urlComponent = URLComponents(string: apiAble.url + apiAble.path)
            
            if apiAble.params != nil {
                urlComponent?.queryItems = apiAble.params?.compactMap{
                    URLQueryItem(name: $0.key, value: $0.value)
                }
            } else {
                guard let intId = apiAble.productId else {
                    return
                }
                
                let productId = "/\(String(intId))"
                
                urlComponent = URLComponents(string: apiAble.url + apiAble.path + productId)
            }
            
            guard let url = urlComponent?.url else {
                return
            }
            
            session.dataTask(with: url) { response in
                guard response.error == nil else {
                    completion(.failure(.error))
                    return
                }
                
                guard successRange.contains(response.statusCode) else {
                    completion(.failure(.statusCode))
                    return
                }
                
                guard let data = response.data else {
                    completion(.failure(.data))
                    return
                }
                completion(.success(data))
            }
        case .post:
            request = makePOSTRequest(apiAble: apiAble)
        case .patch:
            request = makePATCHRequest(apiAble: apiAble)
        case .delete:
            request = makeDELETERequest(apiAble: apiAble)
        }
        
        if apiAble.method != .get {
            guard let request = request else {
                return
            }
            
            session.dataTask(with: request) { response in
                guard response.error == nil else {
                    completion(.failure(.error))
                    return
                }
                
                guard successRange.contains(response.statusCode) else {
                    completion(.failure(.statusCode))
                    return
                }
                
                guard let data = response.data else {
                    completion(.failure(.data))
                    return
                }
                completion(.success(data))
            }
        }
    }
}
```

completionHandler를 활용해서 error, response, data를 비동기로 받아서 이를 내부에서 처리해주고 있다.

보면 return 으로 단순히 콜백을 처리하기 때문에 completion 에서 문제가 났을 경우 어디에서 생겼는지 확인하기 어렵다!

물론 result type를 활용해서 실패에 대한 처리를 할 수 있지만 이는 불편함을 제공하고 있다.

또한 비동기 처리가 늘어날 수록 계속 작성해야할 수도 있는 가능성이 존재한다.

실제 이를 호출하는 곳에서도 아래와 같이 사용해야한다.

```swift
// ListViewController.swift
private func showList(number: Int) {
    let getAPI = List(pageNo: number, itemsPerPage: 20)
    self.networkManager.execute(with: getAPI) { result in
        switch result {
        case .success(let data):
            let decodedData = try? JSONDecoder().decode(ProductsList.self, from: data)
            guard let result = decodedData else { return }
            self.pageNo = result.pageNo
            self.item.append(contentsOf: result.pages)
        case .failure(let error):
            print(error.localizedDescription)
        }
    }
}
```

하지만 async await는 간단해진 코드를 볼 수 있다.

위의 코드와 일부 다른 내용이긴 하지만, 사용하는 방법만 보는 것으로 차이점을 느낄 수 있다.

```swift
final class NetworkManager {
    func fetchWeatherData(urlRequest: URLRequest) async throws -> Weather? {
        guard let url = urlRequest.url else {
            return nil
            
        }
        let (data, response) = try await URLSession.shared.data(from: url)
        
        guard let httpResponse = response as? HTTPURLResponse,
              (200...300).contains(httpResponse.statusCode) else {
                  throw NetWorkError.response
              }
        
        guard let data = try? JSONDecoder().decode(Weather.self, from: data) else {
            throw NetWorkError.decode
        }
        
        return data
    }
}
```

먼저 completionHandler를 사용하지 않고 async 와 throws를 통해 해결해주고 있다.

async 함수를 호출하기 위해서는 await 키워드가 필요하다.

그러므로 더 간단한 코드와 복잡한 로직이 없어지게 된다.

그리고 else 안에서 throw를 통해 completion 에러가 어디에서 났는지 즉각적으로 내보내고 있어서 확인이 쉬워진다.

사용처에서도 다른 것은 코드로 확인할 수 있다.

```swift
private func makeDiary() -> Diary {
    let (title, body) = configureContent()
    var weather: Weather?
    
    Task { () -> Diary in
        guard let urlResponse = WeatherAPI(
            parameters: ["lat": "35",
                        "lon": "139",
                        "appid": "35e629549016019976c1803c71e8fc16"
                        ])
            .makeURLRequest() else {
            
            return Diary(title: title, body: body, createdAt: Date(), weatherIcon: "")
        }
    }
```

Task라는 것으로 일단 async await를 시작할 수 있다.

그 내부에서 필요한 호출을 하게 되면 동작하게 된다.

코드를 보아도 단순해보이고 복잡한 로직이 사라진 것을 볼 수 있다.


나머지는 wwdc를 읽고 더 보강해보도록 하겠다..!

참고사이트

https://sujinnaljin.medium.com/swift-async-await-concurrency-bd7bcf34e26f